/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'pendingCount' : bigint,
  'totalStudents' : bigint,
  'totalTeachers' : bigint,
  'paidCount' : bigint,
  'totalFeesCollectedThisMonth' : bigint,
}
export interface PaymentRecord {
  'id' : string,
  'transactionRef' : string,
  'studentId' : string,
  'note' : string,
  'paymentDate' : Time,
  'amount' : bigint,
}
export type PaymentStatus = { 'Paid' : null } |
  { 'Unpaid' : null } |
  { 'Pending' : null };
export interface Student {
  'id' : string,
  'studentEmail' : string,
  'feeAmount' : bigint,
  'paymentStatus' : PaymentStatus,
  'guardianEmail' : string,
  'enrolledDate' : Time,
  'name' : string,
  'lastPaymentDate' : [] | [Time],
  'parentPhone' : string,
  'className' : string,
  'guardianName' : string,
  'parentName' : string,
}
export interface Teacher {
  'id' : string,
  'subject' : string,
  'name' : string,
  'joiningDate' : Time,
  'isActive' : boolean,
  'email' : string,
  'qualification' : string,
  'contactPhone' : string,
}
export type Time = bigint;
export interface User {
  'userId' : string,
  'name' : string,
  'createdAt' : Time,
  'role' : UserRole,
  'email' : string,
  'phone' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStudent' : ActorMethod<[Student], undefined>,
  'addTeacher' : ActorMethod<[Teacher], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'deleteStudent' : ActorMethod<[string], undefined>,
  'deleteTeacher' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getStudent' : ActorMethod<[string], Student>,
  'getStudentPayments' : ActorMethod<[string], Array<PaymentRecord>>,
  'getTeacher' : ActorMethod<[string], Teacher>,
  'getUser' : ActorMethod<[string], [] | [User]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listPayments' : ActorMethod<[], Array<PaymentRecord>>,
  'listStudents' : ActorMethod<[], Array<Student>>,
  'listStudentsByStatus' : ActorMethod<[PaymentStatus], Array<Student>>,
  'listTeachers' : ActorMethod<[], Array<Teacher>>,
  'listUsers' : ActorMethod<[], Array<User>>,
  'loginUser' : ActorMethod<[string, string], [] | [User]>,
  'recordPayment' : ActorMethod<[PaymentRecord], undefined>,
  'registerUser' : ActorMethod<[string, string, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchStudents' : ActorMethod<[string], Array<Student>>,
  'setupAdmin' : ActorMethod<[string, string, string], string>,
  'updateStudent' : ActorMethod<[string, Student], undefined>,
  'updateTeacher' : ActorMethod<[string, Teacher], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];