/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PaymentStatus = IDL.Variant({
  'Paid' : IDL.Null,
  'Unpaid' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Time = IDL.Int;
export const Student = IDL.Record({
  'id' : IDL.Text,
  'studentEmail' : IDL.Text,
  'feeAmount' : IDL.Nat,
  'paymentStatus' : PaymentStatus,
  'guardianEmail' : IDL.Text,
  'enrolledDate' : Time,
  'name' : IDL.Text,
  'lastPaymentDate' : IDL.Opt(Time),
  'parentPhone' : IDL.Text,
  'className' : IDL.Text,
  'guardianName' : IDL.Text,
  'parentName' : IDL.Text,
});
export const Teacher = IDL.Record({
  'id' : IDL.Text,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'joiningDate' : Time,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'qualification' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'pendingCount' : IDL.Nat,
  'totalStudents' : IDL.Nat,
  'totalTeachers' : IDL.Nat,
  'paidCount' : IDL.Nat,
  'totalFeesCollectedThisMonth' : IDL.Nat,
});
export const PaymentRecord = IDL.Record({
  'id' : IDL.Text,
  'transactionRef' : IDL.Text,
  'studentId' : IDL.Text,
  'note' : IDL.Text,
  'paymentDate' : Time,
  'amount' : IDL.Nat,
});
export const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const User = IDL.Record({
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : UserRole,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStudent' : IDL.Func([Student], [], []),
  'addTeacher' : IDL.Func([Teacher], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'deleteStudent' : IDL.Func([IDL.Text], [], []),
  'deleteTeacher' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getStudent' : IDL.Func([IDL.Text], [Student], ['query']),
  'getStudentPayments' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PaymentRecord)],
      ['query'],
    ),
  'getTeacher' : IDL.Func([IDL.Text], [Teacher], ['query']),
  'getUser' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'listStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'listStudentsByStatus' : IDL.Func(
      [PaymentStatus],
      [IDL.Vec(Student)],
      ['query'],
    ),
  'listTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(User)], []),
  'recordPayment' : IDL.Func([PaymentRecord], [], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchStudents' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'setupAdmin' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'updateStudent' : IDL.Func([IDL.Text, Student], [], []),
  'updateTeacher' : IDL.Func([IDL.Text, Teacher], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PaymentStatus = IDL.Variant({
    'Paid' : IDL.Null,
    'Unpaid' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Time = IDL.Int;
  const Student = IDL.Record({
    'id' : IDL.Text,
    'studentEmail' : IDL.Text,
    'feeAmount' : IDL.Nat,
    'paymentStatus' : PaymentStatus,
    'guardianEmail' : IDL.Text,
    'enrolledDate' : Time,
    'name' : IDL.Text,
    'lastPaymentDate' : IDL.Opt(Time),
    'parentPhone' : IDL.Text,
    'className' : IDL.Text,
    'guardianName' : IDL.Text,
    'parentName' : IDL.Text,
  });
  const Teacher = IDL.Record({
    'id' : IDL.Text,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'joiningDate' : Time,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'qualification' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'pendingCount' : IDL.Nat,
    'totalStudents' : IDL.Nat,
    'totalTeachers' : IDL.Nat,
    'paidCount' : IDL.Nat,
    'totalFeesCollectedThisMonth' : IDL.Nat,
  });
  const PaymentRecord = IDL.Record({
    'id' : IDL.Text,
    'transactionRef' : IDL.Text,
    'studentId' : IDL.Text,
    'note' : IDL.Text,
    'paymentDate' : Time,
    'amount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const User = IDL.Record({
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : UserRole,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStudent' : IDL.Func([Student], [], []),
    'addTeacher' : IDL.Func([Teacher], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'deleteStudent' : IDL.Func([IDL.Text], [], []),
    'deleteTeacher' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getStudent' : IDL.Func([IDL.Text], [Student], ['query']),
    'getStudentPayments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PaymentRecord)],
        ['query'],
      ),
    'getTeacher' : IDL.Func([IDL.Text], [Teacher], ['query']),
    'getUser' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'listStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'listStudentsByStatus' : IDL.Func(
        [PaymentStatus],
        [IDL.Vec(Student)],
        ['query'],
      ),
    'listTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(User)], []),
    'recordPayment' : IDL.Func([PaymentRecord], [], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchStudents' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
    'setupAdmin' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'updateStudent' : IDL.Func([IDL.Text, Student], [], []),
    'updateTeacher' : IDL.Func([IDL.Text, Teacher], [], []),
  });
};

export const init = ({ IDL }) => { return []; };